### ISSUE TITLE
No data fetched in mobile browsers (zalando specific)

### ISSUE THREAD

**Issue by rwitzel** [zalando/catwatch#1]
When I go to http://zalando.github.io/zalando.github.io-dev/ via a browser in a mobile phone
then all numbers are zeros as well as no repositories are shown.

Solution: Provide https://catwatch-web.hackweek.zalan.do with a proper TLS certificate (not a self-signed one).

**Comment by rbarilani** [comment]
+1

**Comment by jbellmann** [comment]
The backend is deployed [here](https://catwatch.opensource.zalan.do/) with valid (not self-signed) certificate.

**Comment by rbarilani** [comment]
@jbellmann cool!

**Comment by jbellmann** [comment]
Oh, I did nothing, just mentioned it here. ;-)

**Comment by rwitzel** [comment]
It works now :-)

Thanks to Alexander and Jan!

**Comment by rbarilani** [comment]
:+1:
