### ISSUE TITLE
Add new spring profile for easy LIVE configuration

### ISSUE THREAD

**Issue by rwitzel** [zalando/catwatch#12]
Benefit: Dockerfile must not be adjusted to pass configuration parameters, i.e. something like the following can be avoided.

CMD java -jar /catwatch-backend.jar -Dspring.database.driverClassName=${SPRING_DATASOURCE_DRIVERCLASSNAME} -Dspring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

**Comment by AlexanderYastrebov** [comment]
Spring boot allows setting properties from environment variables, so there is no need for Docker modification or addition of any new profile.

http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by rwitzel** [comment]
Agree!
