### ISSUE TITLE
Catwatch should use single build system

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/catwatch#13]
I personally vote for maven as for a more standard and wide spread system

**Comment by rwitzel** [comment]
Why?

**Comment by AlexanderYastrebov** [comment]
Because:
1. it is generally harder to maintain both systems simultaneously and to get them in sync
2. it will be a big trouble when lib versions will diverse (occasionally) in two build systems 
3. it basically doubles the amount of time required for CI.
4. there is a lack of some functionality in one system compared to another (e.g. code coverage plugin)

**Comment by rwitzel** [comment]
OK

**Comment by fogfish** [comment]
Build is one dimension here. I would think to package the project into Docker container as well. It gives flexibility to play around with the project.
