### ISSUE TITLE
Database column varchar(255) is not sufficient

### ISSUE THREAD

**Issue by ardoid** [zalando/catwatch#17]
It will result in error, but I don't exactly which column as I change some of them to text.
This should probably be the cause project from Zalando repo not displayed.

**Comment by AlexanderYastrebov** [comment]
Fetching is not working by this reason also

```
18:16:46.900 [http-nio-8080-exec-7] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 22001
18:16:46.900 [http-nio-8080-exec-7] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: value too long for type character varying(255)
```

**Comment by ardoid** [comment]
This is the issue that I am referring to.

**Comment by rwitzel** [comment]
Have you found out what data was too long?

**Comment by AlexanderYastrebov** [comment]
Looking into data after fixing shows it was project.description (https://github.com/zalando/emrclient)

**Comment by rwitzel** [comment]
Thank you for looking into this, Alexander!
