### ISSUE TITLE
Investigate large startup time

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/catwatch#20]
It is possibly due to hibernate schema discovery

```
17:06:05.214 [main] INFO  org.hibernate.Version - HHH000412: Hibernate Core {4.3.10.Final}
17:06:05.219 [main] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
17:06:05.221 [main] INFO  org.hibernate.cfg.Environment - HHH000021: Bytecode provider name : javassist
17:06:05.658 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
17:06:31.766 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
```

**Comment by AlexanderYastrebov** [comment]
http://stackoverflow.com/questions/14445838/hibernate-startup-very-slow

**Comment by rwitzel** [comment]
Yes, Hibernate takes some time to configure itself. We probably won't replace Hibernate for this reason.

**Comment by rwitzel** [comment]
In case the user does not want to use a database (see #26 ), Hibernate should not be configured. This way the startup-time can be drastically improved.

**Comment by jbellmann** [comment]
Just one question, nobody publishes any numbers for 'large startup time'. How long does it need to start up?

**Comment by hjacobs** [comment]
@jbellmann good question, hard numbers please.. :smirk:

**Comment by jbellmann** [comment]
for me its 9 sec in the IDE, with H2 as database

**Comment by lasomethingsomething** [comment]
@hjacobs @jbellmann @rwitzel How should we proceed with this issue?

**Comment by rwitzel** [comment]
:+1: for closing it
