### ISSUE TITLE
Forked repos (non-Zalando projects) should not be shown

### ISSUE THREAD

**Issue by hjacobs** [zalando/catwatch#22]
Forked repositories are currently included in the list of "Zalando's Open Source Projects" (https://zalando.github.io/#repositories), e.g. the "docker-maven-plugin" (https://github.com/zalando-stups/docker-maven-plugin) is not a Zalando-owned project.

We should exclude all forked repositories from CatWatch as they skew the view on what are Zalando's Open Source projects.

**Comment by rwitzel** [comment]
+1

There was already a change in the past to prevent this. It might be that the current code base already excludes forks

**Comment by AlexanderYastrebov** [comment]
I think it was because old build was running on hackweek account. Right now I cant see this fork.
The fix was introduced by  365420c2b2d64ad89458cd9d484c2c69f798b21a

**Comment by hjacobs** [comment]
:+1: looks good (http://zalando.github.io/#repositories)
