### ISSUE TITLE
Develop long-term maintenance strategy (zalando-specific)

### ISSUE THREAD

**Issue by rwitzel** [zalando/catwatch#3]
When I go to http://zalando.github.io/zalando.github.io-dev/ 
then an AWS instance of the the temporary Hackweek account is used as backend.

https://catwatch-web.hackweek.zalan.do

But the backend should run on an AWS instance of a permanent account, should be monitored, updated regularly.

**Comment by Raffo** [comment]
If not used, https://catwatch-web.hackweek.zalan.do/ should be shut down. Live traffic to the app is to https://catwatch.opensource.zalan.do/ .

**Comment by hjacobs** [comment]
@Raffo :+1:

**Comment by hjacobs** [comment]
We need to find a new maintainer (currently it's @janloeffler).

**Comment by hjacobs** [comment]
@rwitzel volunteered to be one of the maintainers for now.

**Comment by rwitzel** [comment]
:+1:  for closing it
