### ISSUE TITLE
Remove graphs?

### ISSUE THREAD

**Issue by hjacobs** [zalando/catwatch#30]
The graphs (http://zalando.github.io/#graphs) currently break the layout and do not look great --- maybe we can hide them until they are "polished"?

**Comment by AlexanderYastrebov** [comment]
Graphs section breaks responsive layout
zalando/zalando.github.io-dev#16

**Comment by hjacobs** [comment]
Let's just hide them for now, I think the page already looks fairly finished and could be promoted when hiding the graphs.

**Comment by rwitzel** [comment]
Closed becuase there is an issue created in zalando.github.io-dev.
