### ISSUE TITLE
Read ".catwatch.yaml" meta information file

### ISSUE THREAD

**Issue by hjacobs** [zalando/catwatch#32]
Proposal: Catwatch should automatically read a `.catwatch.yaml` file in the root of the repository if it's there. This YAML file allows defining a human readable title and a project image (logo):

Example:

``` yaml
title: ZMON Controller
image: https://demo.zmon.io/logo.png
```

**Comment by Raffo** [comment]
Agree.

**Comment by hjacobs** [comment]
Related to #29

**Comment by hjacobs** [comment]
Deployed LIVE and added `.catwatch.yaml` to "senza", check https://catwatch.opensource.zalan.do/projects?organizations=zalando-stups&limit=6&offset=0&sortBy=-score

https://github.com/zalando-stups/senza/blob/master/.catwatch.yaml

**Comment by hjacobs** [comment]
Another example: https://github.com/zalando/zmon/blob/master/.catwatch.yaml
