### ISSUE TITLE
Consider applying a penalty for projects with less than 2 maintainers

### ISSUE THREAD

**Issue by hjacobs** [zalando/catwatch#46]
We should apply score penalties to projects with less than 2 maintainers. This involves changing the "score" function (https://github.com/zalando/catwatch/blob/master/catwatch-backend/src/main/resources/application.properties#L22).

Proposal for the score function:

``` javascript
function(project) {
    var penalty = 0;
    if (project.maintainers.length < 2) {
        penalty = 100;
    }
    return project.forksCount > 0 ? ( project.starsCount + project.forksCount + project.contributorsCount + project.commitsCount / 100 - penalty) : 0;
}
```

**Comment by lasomethingsomething** [comment]
@hjacobs What else do you need to get this idea implemented?

**Comment by hjacobs** [comment]
@LappleApple no real implementation needed, the scoring function is just configuration --- but we need to decide on what we want :smirk:

**Comment by mtrovo** [comment]
Why is this a javascript function?
I see that it's used for updating the function logic at runtime but I don't see a use for it after the logic is stable, shouldn't it just be a concrete implementation of `Scorer#score` method?

**Comment by hjacobs** [comment]
@mtrovo to allow setting the formula via environment variable. I think that's a viable way to go --- other Catwatch users might like to have a different formula (and we are also here in the middle of a discussion of changing it).

**Comment by rbobin** [comment]
Fixed as a part of https://github.com/zalando/catwatch/pull/53
