### ISSUE TITLE
Inconsistent project-naming issue

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/catwatch#52]
On the front/home page, the name of the TechMonkeys project "Gin-OAuth2" is showing up with additional running text in its respective card. Other projects are listed by name-only.

**Comment by Raffo** [comment]
I think it's only a problem in how the .catwatch file is done in that repo. I will fix it there. Please close the issue if it's verify to be fixed later.

**Comment by lasomethingsomething** [comment]
@Raffo will do -- it's also affecting https://github.com/zalando-techmonkeys/gin-gomonitor. So I think this issue will apply to all TM repos...

**Comment by Raffo** [comment]
Chimp works fine ( 💃 ) but I will go through all of them.
