### ISSUE TITLE
ZMON org repos still showing up in rankings

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/catwatch#58]
Hey, can we get rid of those @rbobin? :)

**Comment by lasomethingsomething** [comment]
@rbobin Hi, should I find someone else to do this?

**Comment by rbobin** [comment]
@LappleApple the issue is fixed and can be closed

**Comment by LappleApple** [comment]
Thank you, @rbobin

**Comment by lasomethingsomething** [comment]
Documenting here that the ZMON repos are still showing.

**Comment by rbobin** [comment]
This is frontend issue, here is the link:
https://github.com/zalando-incubator/zalando.github.io-dev/issues/58
