### ISSUE TITLE
Idea for new metrics: Show # of contributions from external and # of contributions to external repos

### ISSUE THREAD

**Issue by alexkops** [zalando/catwatch#59]
Interesting metrics would be:
- Number of commits from users not belonging to the organization(s) to own repositories
- Number of commits from own organization users to repos not belonging to the organization(s)

Not sure if this is possible with the github APIs though.

**Comment by lasomethingsomething** [comment]
Take a look at https://grimoirelab.github.io/ -- these guys are friends, and they have invited us to add some of the metrics to CatWatch. If we have capacity, would be great.

**Comment by jbellmann** [comment]
@alexkops can we close this issue? Fixed with #62, right?

**Comment by alexkops** [comment]
Indeed.
