### ISSUE TITLE
baboon-proxy showing up twice

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/catwatch#61]
Hi there,

If you search the Golang projects you get [BP x 2:](https://zalando.github.io/#repositories?language=Go). Can you take a look?

**Comment by rbarilani** [comment]
@LappleApple Hi Lauri it seems that we have two baboon-proxy projects one under zalando and one under zalando-tech-monkeys organization

**Comment by Raffo** [comment]
@rbarilani As the zalando-techmonkeys org was removed, it can be removed from the list of orgs to crawl.

**Comment by lasomethingsomething** [comment]
@rbarilani Seconding @Raffo. BP2 = "ghost" repo, from the afterlife. Creepy...

**Comment by rbarilani** [comment]
I close this one in favor of: https://github.com/zalando-incubator/zalando.github.io-dev/issues/61
