### ISSUE TITLE
Does catwatch support multiple concurrent fetcher tasks?

### ISSUE THREAD

**Issue by linki** [zalando/catwatch#65]
I'm currently in the process of migrating https://zalando.github.io/ to our Kubernetes setup.

I intend to run at least two replicas (containers) of Catwatch in order to ensure it's available during cluster updates. However, as far as I can see, that would also schedule two concurrent fetcher tasks [1].

My question is: Do I have to fear any undefined behaviour, corrupt data, etc. from running mutiple fetchers or is it safe?

[1] https://github.com/zalando-incubator/catwatch/blob/master/catwatch-backend/src/main/java/org/zalando/catwatch/backend/scheduler/Fetcher.java#L82-L84

**Comment by hjacobs** [comment]
Good question :smile:

**Comment by jbellmann** [comment]
Maybe you can put the 'Fetcher'-part into an [CommandLineRunner](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/CommandLineRunner.html) and run the same image as an k8s-cronjob to fetch latest data and shutdown the app. Would like to try out if you want.  Cronjobs are supported by K8s, right? Reuse what's already there.

Regards

**Comment by hjacobs** [comment]
Using the CronJob feature in Kubernetes would be nice, yes.

**Comment by jbellmann** [comment]
Ok, I will try it.

**Comment by rwitzel** [comment]
@linki Catwatch was not explicitly designed to support concurrent fetcher tasks.

In ProjectRepositoryImpl you can see that the query for recent projects looks for latest saved snapshot, then it queries the data for this snapshot. 
```
        DateTimeSubQuery<Date> lastSnapshot = new JPASubQuery().from(project)
            .where(project.organizationName.eq(organization))
            .unique(project.snapshotDate.max());
       ...

        BooleanBuilder q = new BooleanBuilder()
            .and(project.organizationName.eq(organization))
            .and(project.snapshotDate.eq(lastSnapshot));
       ...
        return queryProject().where(q).list(project);
```

In case two fetcher tasks use the exact same snapshot, the each project is listed twice in the results.

Thus a cron job would be much better.

**Comment by jbellmann** [comment]
Could someone add me as contributor for this repo. I forgot to make a fork and want to push my branch now.

```
Permission to zalando-incubator/catwatch.git denied to jbellmann.
```

Thanks

**Comment by mikkeloscar** [comment]
@jbellmann I added you!

**Comment by linki** [comment]
@jbellmann @rwitzel Thanks for following up 👍
